# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Site Names Are Hard
email: greg@gregconant.com
description: > # this means to ignore newlines until "baseurl:"
  This site is intended to be a collection of my thoughts and findings
  about technical things that I am thinking about and want to record for later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gregmconant
github_username:  gregconant

# Build settings
markdown: kramdown
