# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg Conant
email: greg@gregconant.com
description:  I am a software developer. These are my thoughts and findings about technical things that I find noteworthy, or am otherwise bound to forget.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gregconant.github.io" # the base hostname & protocol for your site
twitter_username: gregmconant
github_username:  gregconant
post_limit: 5
footer_left: "Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"

# Build settings
markdown: kramdown
